services:
  postgres:
    image: postgres:17
    env_file:
      - .env
      - .env.local
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]
  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
  smtp4dev:
    # see: https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml
    image: rnwood/smtp4dev:latest
    ports:
      - "${SMTP_WEB_INTERFACE_PORT}:80"
      - "${SMTP_PORT}:25"
    environment:
      - RelayOptions__Login=${SMTP_USERNAME}
      - RelayOptions__Password=${SMTP_PASSWORD}
    volumes:
      - smtp_data:/smtp4dev
volumes:
  postgres_data: {}
  redis_data: {}
  smtp_data: {}
